import type { CardDefinition, PlayerId } from "@cardforge/card-schema";
import { stateHash } from "@cardforge/rules-kernel";
import { competitiveExpansionCards } from "./competitive-cards.js";
import { launchExpansionCards } from "./launch-cards.js";

const rawProofCards = [
  {
    cardId: "leader.vanguard",
    revision: 1,
    name: "Marshal Ilyra",
    type: "leader",
    aspects: ["force", "bastion"],
    focusCost: 0,
    playTime: 0,
    abilities: [
      {
        abilityId: "marshal-command",
        type: "leader_command",
        focusCost: 1,
        timeCost: 2,
        oncePerCycle: true,
        effects: [
          { op: "deal_damage", target: { kind: "enemy_leader" }, amount: 1 },
        ],
      },
    ],
  },
  {
    cardId: "leader.relay",
    revision: 2,
    name: "Kestrel Vey",
    type: "leader",
    aspects: ["motion", "cunning"],
    focusCost: 0,
    playTime: 0,
    abilities: [
      {
        abilityId: "vector-command",
        type: "leader_command",
        focusCost: 1,
        timeCost: 2,
        oncePerCycle: true,
        effects: [{ op: "draw", amount: 1 }],
      },
    ],
  },
  {
    cardId: "leader.rootbound",
    revision: 1,
    name: "Nera Rootbound",
    type: "leader",
    aspects: ["growth", "entropy"],
    focusCost: 0,
    playTime: 0,
    abilities: [
      {
        abilityId: "renew-command",
        type: "leader_command",
        focusCost: 1,
        timeCost: 2,
        oncePerCycle: true,
        effects: [
          { op: "heal", target: { kind: "friendly_leader" }, amount: 2 },
        ],
      },
    ],
  },
  {
    cardId: "leader.skydancer",
    revision: 1,
    name: "Arlen Skydancer",
    type: "leader",
    aspects: ["force", "motion"],
    focusCost: 0,
    playTime: 0,
    abilities: [
      {
        abilityId: "survey-command",
        type: "leader_command",
        focusCost: 1,
        timeCost: 2,
        oncePerCycle: true,
        effects: [{ op: "scout", amount: 2 }],
      },
    ],
  },
  {
    cardId: "leader.proof",
    revision: 1,
    name: "Proof Marshal",
    type: "leader",
    aspects: ["force", "bastion", "motion", "growth", "cunning", "entropy"],
    focusCost: 0,
    playTime: 0,
  },
  {
    cardId: "entity.linebreaker",
    revision: 1,
    name: "Linebreaker",
    type: "entity",
    aspects: ["force"],
    focusCost: 2,
    playTime: 2,
    power: 2,
    vitality: 3,
    presence: 1,
    strikeTime: 3,
  },
  {
    cardId: "entity.skywatcher",
    revision: 2,
    name: "Skywatcher",
    type: "entity",
    aspects: ["motion"],
    focusCost: 3,
    playTime: 3,
    power: 2,
    vitality: 3,
    presence: 2,
    strikeTime: 3,
    keywords: { ranged: true },
  },
  {
    cardId: "entity.bulwark",
    revision: 2,
    name: "Bulwark Array",
    type: "entity",
    subtypes: ["structure"],
    aspects: ["bastion"],
    focusCost: 3,
    playTime: 3,
    power: 0,
    vitality: 6,
    presence: 2,
    strikeTime: 3,
    keywords: { structure: true },
    slotRestriction: "support",
  },
  {
    cardId: "entity.flashrunner",
    revision: 2,
    name: "Flashrunner",
    type: "entity",
    aspects: ["motion"],
    focusCost: 2,
    playTime: 2,
    power: 2,
    vitality: 2,
    presence: 2,
    strikeTime: 2,
    keywords: { rapid: true, mobile: true },
  },
  {
    cardId: "entity.ironhide",
    revision: 1,
    name: "Ironhide Guard",
    type: "entity",
    aspects: ["bastion"],
    focusCost: 3,
    playTime: 3,
    power: 2,
    vitality: 4,
    presence: 2,
    strikeTime: 3,
    keywords: { armor: 1 },
  },
  {
    cardId: "entity.aegis",
    revision: 1,
    name: "Aegis Initiate",
    type: "entity",
    aspects: ["bastion"],
    focusCost: 2,
    playTime: 2,
    power: 1,
    vitality: 3,
    presence: 2,
    strikeTime: 3,
    keywords: { barrier: true },
  },
  {
    cardId: "tactic.impact",
    revision: 1,
    name: "Focused Impact",
    type: "tactic",
    aspects: ["force"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "impact",
        type: "activated",
        effects: [
          {
            op: "deal_damage",
            target: { kind: "chosen_enemy_entity" },
            amount: 3,
          },
        ],
      },
    ],
  },
  {
    cardId: "tactic.mend",
    revision: 1,
    name: "Field Mend",
    type: "tactic",
    aspects: ["growth"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "mend",
        type: "activated",
        effects: [
          { op: "heal", target: { kind: "chosen_friendly_entity" }, amount: 3 },
        ],
      },
    ],
  },
  {
    cardId: "tactic.reposition",
    revision: 1,
    name: "Reposition",
    type: "tactic",
    aspects: ["motion"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "reposition",
        type: "activated",
        effects: [{ op: "shift", target: { kind: "chosen_friendly_entity" } }],
      },
    ],
  },
  {
    cardId: "tactic.displace",
    revision: 1,
    name: "Forced Displacement",
    type: "tactic",
    aspects: ["cunning"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "displace",
        type: "activated",
        effects: [{ op: "shift", target: { kind: "chosen_enemy_entity" } }],
      },
    ],
  },
  {
    cardId: "entity.broodcaller",
    revision: 1,
    name: "Broodcaller",
    type: "entity",
    aspects: ["growth"],
    focusCost: 3,
    playTime: 3,
    power: 2,
    vitality: 4,
    presence: 1,
    strikeTime: 3,
    abilities: [
      {
        abilityId: "brood",
        type: "triggered",
        trigger: "on_deploy",
        effects: [
          {
            op: "optional_focus",
            amount: 1,
            effects: [{ op: "spawn", tokenCardId: "token.sprout" }],
          },
        ],
      },
    ],
  },
  {
    cardId: "token.sprout",
    revision: 1,
    name: "Sprout",
    type: "token",
    aspects: ["growth"],
    focusCost: 0,
    playTime: 0,
    power: 1,
    vitality: 1,
    presence: 1,
    strikeTime: 3,
    generatedOnly: true,
  },
  {
    cardId: "attachment.edge",
    revision: 1,
    name: "Tempered Edge",
    type: "attachment",
    aspects: ["force"],
    focusCost: 1,
    playTime: 1,
    staticModifiers: { power: 1 },
    abilities: [{ abilityId: "edge", type: "static", effects: [] }],
  },
  {
    cardId: "relic.beacon",
    revision: 1,
    name: "Signal Beacon",
    type: "relic",
    aspects: ["neutral"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "beacon",
        type: "activated",
        timeCost: 1,
        oncePerCycle: true,
        effects: [{ op: "scout", amount: 2 }],
      },
    ],
  },
  {
    cardId: "site.overlook",
    revision: 1,
    name: "High Overlook",
    type: "site",
    aspects: ["neutral"],
    focusCost: 2,
    playTime: 2,
    staticModifiers: { presence: 1 },
    abilities: [{ abilityId: "overlook", type: "static", effects: [] }],
  },
  {
    cardId: "reaction.deflect",
    revision: 1,
    name: "Deflect",
    type: "reaction",
    aspects: ["bastion"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "deflect",
        type: "reaction",
        tempoDebt: 1,
        effects: [
          { op: "add_barrier", target: { kind: "chosen_friendly_entity" } },
        ],
      },
    ],
  },
  {
    cardId: "reaction.denial",
    revision: 1,
    name: "Hard Denial",
    type: "reaction",
    aspects: ["cunning"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "denial",
        type: "reaction",
        tempoDebt: 2,
        effects: [{ op: "cancel_previous_chain_link" }],
      },
    ],
  },
  {
    cardId: "tactic.recover",
    revision: 1,
    name: "Recover the Fallen",
    type: "tactic",
    aspects: ["entropy"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "recover",
        type: "activated",
        effects: [{ op: "salvage", cardType: "entity" }],
      },
    ],
  },
  {
    cardId: "tactic.survey",
    revision: 1,
    name: "Survey the Line",
    type: "tactic",
    aspects: ["motion"],
    focusCost: 1,
    playTime: 1,
    prepareDiscount: 1,
    abilities: [
      {
        abilityId: "survey",
        type: "activated",
        effects: [{ op: "scout", amount: 3 }],
      },
    ],
  },
  {
    cardId: "entity.lastlight",
    revision: 1,
    name: "Lastlight Warden",
    type: "entity",
    aspects: ["entropy"],
    focusCost: 2,
    playTime: 2,
    power: 2,
    vitality: 2,
    presence: 1,
    strikeTime: 3,
    abilities: [
      {
        abilityId: "lastlight",
        type: "triggered",
        trigger: "on_defeat",
        effects: [
          { op: "heal", target: { kind: "friendly_leader" }, amount: 2 },
        ],
      },
    ],
  },
  {
    cardId: "tactic.stagger",
    revision: 1,
    name: "Staggering Pulse",
    type: "tactic",
    aspects: ["cunning"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "stagger",
        type: "activated",
        effects: [
          {
            op: "add_status",
            target: { kind: "chosen_enemy_entity" },
            status: {
              statusId: "stunned",
              value: 1,
              duration: "until_refresh",
              stackingPolicy: "refresh",
            },
          },
        ],
      },
    ],
  },
  {
    cardId: "tactic.crossfire",
    revision: 1,
    name: "Crossfire",
    type: "tactic",
    aspects: ["force"],
    focusCost: 3,
    playTime: 3,
    abilities: [
      {
        abilityId: "crossfire",
        type: "activated",
        effects: [
          {
            op: "deal_damage",
            target: {
              kind: "chosen_enemy_entities",
              minimum: 1,
              maximum: 2,
            },
            amount: 2,
          },
        ],
      },
    ],
  },
  {
    cardId: "tactic.adapt",
    revision: 1,
    name: "Adapt the Plan",
    type: "tactic",
    aspects: ["growth"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "adapt",
        type: "activated",
        effects: [
          {
            op: "choose_one",
            options: [
              {
                optionId: "recover",
                effects: [
                  {
                    op: "heal",
                    target: { kind: "friendly_leader" },
                    amount: 2,
                  },
                ],
              },
              {
                optionId: "resupply",
                effects: [{ op: "draw", amount: 1 }],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    cardId: "entity.emberlance",
    revision: 1,
    name: "Emberlance Raider",
    type: "entity",
    subtypes: ["soldier"],
    aspects: ["force"],
    focusCost: 3,
    playTime: 3,
    power: 4,
    vitality: 2,
    presence: 1,
    strikeTime: 3,
  },
  {
    cardId: "entity.breachsmith",
    revision: 1,
    name: "Breachsmith",
    type: "entity",
    subtypes: ["soldier"],
    aspects: ["force"],
    focusCost: 2,
    playTime: 2,
    power: 2,
    vitality: 2,
    presence: 1,
    strikeTime: 2,
    keywords: { rapid: true },
  },
  {
    cardId: "entity.rampart_keeper",
    revision: 2,
    name: "Rampart Keeper",
    type: "entity",
    subtypes: ["guardian"],
    aspects: ["bastion"],
    focusCost: 4,
    playTime: 3,
    power: 2,
    vitality: 6,
    presence: 2,
    strikeTime: 3,
    keywords: { armor: 1 },
  },
  {
    cardId: "tactic.break_line",
    revision: 1,
    name: "Break the Line",
    type: "tactic",
    aspects: ["force"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "break-line",
        type: "activated",
        effects: [
          {
            op: "deal_damage",
            target: { kind: "chosen_enemy_entity" },
            amount: 1,
          },
        ],
      },
    ],
  },
  {
    cardId: "entity.windknife",
    revision: 2,
    name: "Windknife Courier",
    type: "entity",
    subtypes: ["scout"],
    aspects: ["motion"],
    focusCost: 2,
    playTime: 2,
    power: 1,
    vitality: 3,
    presence: 2,
    strikeTime: 2,
    keywords: { mobile: true, ranged: true },
  },
  {
    cardId: "entity.codebreaker",
    revision: 1,
    name: "Cipher Duelist",
    type: "entity",
    subtypes: ["agent"],
    aspects: ["cunning"],
    focusCost: 3,
    playTime: 3,
    power: 2,
    vitality: 4,
    presence: 1,
    strikeTime: 3,
  },
  {
    cardId: "tactic.quickstep",
    revision: 1,
    name: "Quickstep Route",
    type: "tactic",
    aspects: ["motion"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "quickstep",
        type: "activated",
        effects: [{ op: "shift", target: { kind: "chosen_friendly_entity" } }],
      },
    ],
  },
  {
    cardId: "tactic.false_order",
    revision: 1,
    name: "False Order",
    type: "tactic",
    aspects: ["cunning"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "false-order",
        type: "activated",
        effects: [
          {
            op: "add_status",
            target: { kind: "chosen_enemy_entity" },
            status: {
              statusId: "rooted",
              value: 1,
              duration: "until_refresh",
              stackingPolicy: "refresh",
            },
          },
        ],
      },
    ],
  },
  {
    cardId: "reaction.misdirect",
    revision: 1,
    name: "Misdirection",
    type: "reaction",
    aspects: ["cunning"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "misdirect",
        type: "reaction",
        tempoDebt: 1,
        effects: [{ op: "shift", target: { kind: "chosen_friendly_entity" } }],
      },
    ],
  },
  {
    cardId: "entity.mossback",
    revision: 1,
    name: "Mossback Tender",
    type: "entity",
    subtypes: ["beast"],
    aspects: ["growth"],
    focusCost: 3,
    playTime: 3,
    power: 2,
    vitality: 5,
    presence: 2,
    strikeTime: 3,
  },
  {
    cardId: "entity.seedwarden",
    revision: 1,
    name: "Seedwarden",
    type: "entity",
    subtypes: ["guardian"],
    aspects: ["growth"],
    focusCost: 2,
    playTime: 2,
    power: 1,
    vitality: 3,
    presence: 2,
    strikeTime: 3,
  },
  {
    cardId: "entity.ashcollector",
    revision: 1,
    name: "Ash Collector",
    type: "entity",
    subtypes: ["reclaimer"],
    aspects: ["entropy"],
    focusCost: 2,
    playTime: 2,
    power: 2,
    vitality: 2,
    presence: 1,
    strikeTime: 3,
    abilities: [
      {
        abilityId: "last-account",
        type: "triggered",
        trigger: "on_defeat",
        effects: [{ op: "draw", amount: 1 }],
      },
    ],
  },
  {
    cardId: "entity.gravetender",
    revision: 1,
    name: "Gravetender",
    type: "entity",
    subtypes: ["reclaimer"],
    aspects: ["entropy"],
    focusCost: 4,
    playTime: 3,
    power: 3,
    vitality: 5,
    presence: 2,
    strikeTime: 3,
  },
  {
    cardId: "tactic.regrowth",
    revision: 1,
    name: "Patient Regrowth",
    type: "tactic",
    aspects: ["growth"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "regrowth",
        type: "activated",
        effects: [
          { op: "heal", target: { kind: "chosen_friendly_entity" }, amount: 2 },
        ],
      },
    ],
  },
  {
    cardId: "tactic.culling_mark",
    revision: 1,
    name: "Culling Mark",
    type: "tactic",
    aspects: ["entropy"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "culling-mark",
        type: "activated",
        effects: [
          {
            op: "add_status",
            target: { kind: "chosen_enemy_entity" },
            status: {
              statusId: "exposed",
              value: 1,
              duration: "until_cycle_end",
              stackingPolicy: "highest",
            },
          },
        ],
      },
    ],
  },
  {
    cardId: "tactic.return_cycle",
    revision: 1,
    name: "Return to the Cycle",
    type: "tactic",
    aspects: ["entropy"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "return-cycle",
        type: "activated",
        effects: [{ op: "salvage", cardType: "entity" }],
      },
    ],
  },
  {
    cardId: "entity.coalheart",
    revision: 1,
    name: "Coalheart Vanguard",
    type: "entity",
    subtypes: ["soldier"],
    aspects: ["force"],
    focusCost: 4,
    playTime: 3,
    power: 5,
    vitality: 4,
    presence: 1,
    strikeTime: 3,
  },
  {
    cardId: "entity.torchline",
    revision: 1,
    name: "Torchline Skirmisher",
    type: "entity",
    subtypes: ["soldier"],
    aspects: ["force"],
    focusCost: 1,
    playTime: 2,
    power: 1,
    vitality: 2,
    presence: 1,
    strikeTime: 2,
    keywords: { rapid: true },
  },
  {
    cardId: "entity.gatehouse",
    revision: 2,
    name: "Gatehouse Sentinel",
    type: "entity",
    subtypes: ["guardian"],
    aspects: ["bastion"],
    focusCost: 3,
    playTime: 3,
    power: 1,
    vitality: 5,
    presence: 2,
    strikeTime: 3,
    keywords: { armor: 1 },
  },
  {
    cardId: "entity.watchtower",
    revision: 1,
    name: "Forward Watchtower",
    type: "entity",
    subtypes: ["structure"],
    aspects: ["bastion"],
    focusCost: 2,
    playTime: 2,
    power: 0,
    vitality: 4,
    presence: 2,
    strikeTime: 3,
    keywords: { structure: true },
    slotRestriction: "support",
  },
  {
    cardId: "entity.slipstream",
    revision: 2,
    name: "Slipstream Lancer",
    type: "entity",
    subtypes: ["scout"],
    aspects: ["motion"],
    focusCost: 3,
    playTime: 2,
    power: 3,
    vitality: 3,
    presence: 2,
    strikeTime: 2,
    keywords: { mobile: true },
  },
  {
    cardId: "entity.horizon_spotter",
    revision: 2,
    name: "Horizon Spotter",
    type: "entity",
    subtypes: ["scout"],
    aspects: ["motion"],
    focusCost: 2,
    playTime: 2,
    power: 1,
    vitality: 2,
    presence: 2,
    strikeTime: 2,
    keywords: { ranged: true },
  },
  {
    cardId: "entity.thornroot",
    revision: 1,
    name: "Thornroot Colossus",
    type: "entity",
    subtypes: ["beast"],
    aspects: ["growth"],
    focusCost: 5,
    playTime: 4,
    power: 4,
    vitality: 7,
    presence: 3,
    strikeTime: 4,
  },
  {
    cardId: "entity.mycelial_guide",
    revision: 1,
    name: "Mycelial Guide",
    type: "entity",
    subtypes: ["reclaimer"],
    aspects: ["growth"],
    focusCost: 2,
    playTime: 2,
    power: 1,
    vitality: 4,
    presence: 2,
    strikeTime: 3,
    abilities: [
      {
        abilityId: "restorative-arrival",
        type: "triggered",
        trigger: "on_deploy",
        effects: [
          { op: "heal", target: { kind: "friendly_leader" }, amount: 1 },
        ],
      },
    ],
  },
  {
    cardId: "entity.veil_analyst",
    revision: 1,
    name: "Veil Analyst",
    type: "entity",
    subtypes: ["agent"],
    aspects: ["cunning"],
    focusCost: 3,
    playTime: 3,
    power: 1,
    vitality: 4,
    presence: 1,
    strikeTime: 3,
    abilities: [
      {
        abilityId: "field-analysis",
        type: "triggered",
        trigger: "on_deploy",
        effects: [{ op: "scout", amount: 2 }],
      },
    ],
  },
  {
    cardId: "entity.quiet_saboteur",
    revision: 1,
    name: "Quiet Saboteur",
    type: "entity",
    subtypes: ["agent"],
    aspects: ["cunning"],
    focusCost: 2,
    playTime: 2,
    power: 1,
    vitality: 2,
    presence: 1,
    strikeTime: 2,
    keywords: { rapid: true },
  },
  {
    cardId: "entity.carrion_broker",
    revision: 1,
    name: "Carrion Broker",
    type: "entity",
    subtypes: ["reclaimer"],
    aspects: ["entropy"],
    focusCost: 3,
    playTime: 3,
    power: 3,
    vitality: 3,
    presence: 1,
    strikeTime: 3,
    abilities: [
      {
        abilityId: "death-dividend",
        type: "triggered",
        trigger: "on_defeat",
        effects: [{ op: "salvage", cardType: "entity" }],
      },
    ],
  },
  {
    cardId: "entity.hollow_colossus",
    revision: 1,
    name: "Hollow Colossus",
    type: "entity",
    subtypes: ["beast"],
    aspects: ["entropy"],
    focusCost: 5,
    playTime: 4,
    power: 5,
    vitality: 6,
    presence: 2,
    strikeTime: 4,
  },
  {
    cardId: "reaction.counterstrike",
    revision: 1,
    name: "Counterstrike",
    type: "reaction",
    aspects: ["force"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "counterstrike",
        type: "reaction",
        tempoDebt: 1,
        effects: [
          {
            op: "deal_damage",
            target: { kind: "chosen_enemy_entity" },
            amount: 1,
          },
        ],
      },
    ],
  },
  {
    cardId: "reaction.second_wind",
    revision: 1,
    name: "Second Wind",
    type: "reaction",
    aspects: ["growth"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "second-wind",
        type: "reaction",
        tempoDebt: 1,
        effects: [
          { op: "heal", target: { kind: "chosen_friendly_entity" }, amount: 2 },
        ],
      },
    ],
  },
  {
    cardId: "attachment.command_standard",
    revision: 1,
    name: "Command Standard",
    type: "attachment",
    aspects: ["bastion"],
    focusCost: 2,
    playTime: 2,
    staticModifiers: { presence: 1 },
    abilities: [{ abilityId: "command-standard", type: "static", effects: [] }],
  },
  {
    cardId: "attachment.wild_graft",
    revision: 1,
    name: "Wild Graft",
    type: "attachment",
    aspects: ["growth"],
    focusCost: 2,
    playTime: 2,
    staticModifiers: { power: 1, presence: 1 },
    abilities: [{ abilityId: "wild-graft", type: "static", effects: [] }],
  },
  {
    cardId: "relic.memory_lattice",
    revision: 1,
    name: "Memory Lattice",
    type: "relic",
    aspects: ["cunning"],
    focusCost: 3,
    playTime: 3,
    abilities: [
      {
        abilityId: "lattice-draw",
        type: "activated",
        focusCost: 1,
        timeCost: 1,
        oncePerCycle: true,
        effects: [{ op: "draw", amount: 1 }],
      },
    ],
  },
  {
    cardId: "site.convergence",
    revision: 1,
    name: "Convergence Well",
    type: "site",
    aspects: ["neutral"],
    focusCost: 3,
    playTime: 3,
    staticModifiers: { presence: 2 },
    abilities: [{ abilityId: "convergence", type: "static", effects: [] }],
  },
] as const satisfies readonly CardDefinition[];

const completeCardSource: readonly CardDefinition[] = [
  ...rawProofCards,
  ...competitiveExpansionCards,
  ...launchExpansionCards,
];

const ordinaryCollectibles = completeCardSource.filter(
  (card) =>
    card.type !== "leader" && !card.generatedOnly && card.rarity !== "unique",
);
if (ordinaryCollectibles.length !== 152)
  throw new Error("Launch rarity curve requires 152 ordinary collectibles");
const ordinaryRarity = new Map(
  ordinaryCollectibles.map(
    (card, index) =>
      [
        card.cardId,
        index < 72 ? "common" : index < 120 ? "uncommon" : "rare",
      ] as const,
  ),
);
let collectorNumber = 0;
export const proofCards: readonly CardDefinition[] = completeCardSource.map(
  (card) => {
    const productionCard =
      card.cardId !== "leader.proof" && !card.generatedOnly;
    if (productionCard) collectorNumber += 1;
    return {
      ...card,
      ...(card.type === "leader" || card.generatedOnly
        ? {}
        : { rarity: card.rarity ?? ordinaryRarity.get(card.cardId)! }),
      ...(productionCard
        ? { collectorNumber: String(collectorNumber).padStart(3, "0") }
        : {}),
      budgetScore:
        card.focusCost +
        (card.power ?? 0) +
        (card.vitality ?? 0) * 0.8 +
        (card.presence ?? 0) * 1.3,
      complexityScore:
        (card.abilities?.length ?? 0) +
        Object.keys(card.keywords ?? {}).length +
        (card.unique ? 1 : 0),
      setId: "core-prototype",
      release: { state: "published", availableFrom: "2026-08-16" },
    };
  },
);

export const prototypeCards: readonly CardDefinition[] = proofCards.filter(
  (card) =>
    card.cardId !== "leader.proof" &&
    !("generatedOnly" in card && card.generatedOnly),
);

export const proofCardMap: ReadonlyMap<string, CardDefinition> = new Map(
  proofCards.map((card) => [card.cardId, card]),
);
export const proofContentHash = stateHash(proofCards);
export const proofLeaders = {
  p1: "leader.proof",
  p2: "leader.proof",
} as const;

export const prototypeLeaderOptions = [
  {
    cardId: "leader.ember",
    archetype: "Breakthrough",
    summary: "Mono-Force attackers that convert open Fronts into Core damage.",
  },
  {
    cardId: "leader.citadel",
    archetype: "Citadel",
    summary: "Mono-Bastion armor, barriers, Structures, and Presence.",
  },
  {
    cardId: "leader.vector",
    archetype: "Relay",
    summary: "Mono-Motion shifting, ranged pressure, and timeline efficiency.",
  },
  {
    cardId: "leader.verdant",
    archetype: "Brood",
    summary: "Mono-Growth tokens, healing, and durable Front development.",
  },
  {
    cardId: "leader.cipher",
    archetype: "Protocol",
    summary: "Mono-Cunning preparation, selection, and bounded denial.",
  },
  {
    cardId: "leader.hollow",
    archetype: "Afterlife",
    summary: "Mono-Entropy attrition and recurring defeated Entities.",
  },
  {
    cardId: "leader.vanguard",
    archetype: "Siege",
    summary: "Force/Bastion pressure with direct Core damage.",
  },
  {
    cardId: "leader.relay",
    archetype: "Ambush",
    summary: "Motion/Cunning positioning and response control.",
  },
  {
    cardId: "leader.rootbound",
    archetype: "Reclamation",
    summary: "Growth/Entropy recovery and defeat value.",
  },
  {
    cardId: "leader.skydancer",
    archetype: "Raid",
    summary: "Force/Motion attacks backed by card selection.",
  },
  {
    cardId: "leader.sanctuary",
    archetype: "Sanctuary",
    summary: "Bastion/Growth healing backed by overwhelming Presence.",
  },
  {
    cardId: "leader.null",
    archetype: "Null Control",
    summary: "Cunning/Entropy disruption, exposure, and recursion.",
  },
] as const;

export type PrototypeLeaderId =
  (typeof prototypeLeaderOptions)[number]["cardId"];

function buildStarterDeck(cardIds: readonly string[]): readonly string[] {
  if (cardIds.length !== 14)
    throw new Error("Prototype starter decks require exactly 14 card IDs");
  return cardIds.flatMap((cardId, index) =>
    Array.from({ length: index < 12 ? 3 : 2 }, () => cardId),
  );
}

export const prototypeDecks: Readonly<
  Record<PrototypeLeaderId, readonly string[]>
> = {
  "leader.ember": buildStarterDeck([
    "entity.linebreaker",
    "entity.emberlance",
    "entity.coalheart",
    "entity.torchline",
    "entity.redline_duelist",
    "entity.ashwing_raider",
    "entity.banner_breaker",
    "entity.flare_captain",
    "tactic.impact",
    "tactic.scorch_lane",
    "reaction.counterstrike",
    "reaction.answer_with_force",
    "attachment.breach_charge",
    "relic.field_compass",
  ]),
  "leader.citadel": buildStarterDeck([
    "entity.bulwark",
    "entity.ironhide",
    "entity.aegis",
    "entity.gatehouse",
    "entity.oathshield",
    "entity.citadel_archer",
    "entity.granite_warden",
    "entity.wallwright",
    "reaction.deflect",
    "tactic.hold_the_center",
    "reaction.brace_for_impact",
    "attachment.command_standard",
    "relic.citadel_bell",
    "site.crossroads",
  ]),
  "leader.vector": buildStarterDeck([
    "entity.skywatcher",
    "entity.flashrunner",
    "entity.windknife",
    "entity.slipstream",
    "entity.vector_scout",
    "entity.gale_marksman",
    "entity.relay_rider",
    "entity.crosswind_ace",
    "tactic.reposition",
    "tactic.slip_the_net",
    "reaction.moving_guard",
    "attachment.vector_rig",
    "relic.field_compass",
    "site.overlook",
  ]),
  "leader.verdant": buildStarterDeck([
    "entity.broodcaller",
    "entity.mossback",
    "entity.seedwarden",
    "entity.thornroot",
    "entity.sprout_tender",
    "entity.grove_healer",
    "entity.pollen_guard",
    "entity.nest_shepherd",
    "tactic.mend",
    "tactic.abundant_return",
    "reaction.second_wind",
    "reaction.sheltering_bloom",
    "relic.seed_vault",
    "site.crossroads",
  ]),
  "leader.cipher": buildStarterDeck([
    "entity.codebreaker",
    "entity.veil_analyst",
    "entity.quiet_saboteur",
    "entity.whisper_agent",
    "entity.glasswire_sniper",
    "entity.signal_thief",
    "entity.null_magistrate",
    "entity.reserve_handler",
    "tactic.displace",
    "tactic.read_the_field",
    "reaction.denial",
    "reaction.sealed_verdict",
    "attachment.whisper_key",
    "relic.memory_lattice",
  ]),
  "leader.hollow": buildStarterDeck([
    "entity.lastlight",
    "entity.ashcollector",
    "entity.gravetender",
    "entity.carrion_broker",
    "entity.dusk_scavenger",
    "entity.rot_marshal",
    "entity.memory_eater",
    "entity.endless_husk",
    "tactic.recover",
    "tactic.wither",
    "reaction.deny_the_end",
    "relic.ossuary_engine",
    "entity.common_guard",
    "site.convergence",
  ]),
  "leader.vanguard": buildStarterDeck([
    "entity.linebreaker",
    "entity.ironhide",
    "entity.emberlance",
    "entity.rampart_keeper",
    "entity.coalheart",
    "entity.torchline",
    "entity.gatehouse",
    "entity.watchtower",
    "tactic.impact",
    "reaction.deflect",
    "reaction.counterstrike",
    "attachment.command_standard",
    "relic.beacon",
    "site.convergence",
  ]),
  "leader.relay": buildStarterDeck([
    "entity.skywatcher",
    "entity.flashrunner",
    "entity.windknife",
    "entity.codebreaker",
    "entity.slipstream",
    "entity.horizon_spotter",
    "entity.veil_analyst",
    "entity.quiet_saboteur",
    "tactic.survey",
    "reaction.denial",
    "reaction.misdirect",
    "relic.memory_lattice",
    "tactic.quickstep",
    "site.convergence",
  ]),
  "leader.rootbound": buildStarterDeck([
    "entity.broodcaller",
    "entity.lastlight",
    "entity.mossback",
    "entity.ashcollector",
    "entity.thornroot",
    "entity.mycelial_guide",
    "entity.carrion_broker",
    "entity.hollow_colossus",
    "tactic.adapt",
    "reaction.second_wind",
    "attachment.wild_graft",
    "tactic.regrowth",
    "relic.beacon",
    "site.convergence",
  ]),
  "leader.skydancer": buildStarterDeck([
    "entity.linebreaker",
    "entity.flashrunner",
    "entity.emberlance",
    "entity.windknife",
    "entity.coalheart",
    "entity.torchline",
    "entity.slipstream",
    "entity.horizon_spotter",
    "tactic.impact",
    "tactic.crossfire",
    "reaction.counterstrike",
    "tactic.quickstep",
    "relic.beacon",
    "site.convergence",
  ]),
  "leader.sanctuary": buildStarterDeck([
    "entity.ironhide",
    "entity.gatehouse",
    "entity.oathshield",
    "entity.wallwright",
    "entity.broodcaller",
    "entity.mossback",
    "entity.grove_healer",
    "entity.pollen_guard",
    "tactic.hold_the_center",
    "reaction.brace_for_impact",
    "tactic.mend",
    "reaction.sheltering_bloom",
    "relic.seed_vault",
    "site.crossroads",
  ]),
  "leader.null": buildStarterDeck([
    "entity.codebreaker",
    "entity.veil_analyst",
    "entity.glasswire_sniper",
    "entity.reserve_handler",
    "entity.lastlight",
    "entity.ashcollector",
    "entity.rot_marshal",
    "entity.grave_choir",
    "tactic.displace",
    "reaction.sealed_verdict",
    "tactic.wither",
    "reaction.deny_the_end",
    "relic.memory_lattice",
    "relic.ossuary_engine",
  ]),
};

export const defaultPrototypeLeaders = {
  p1: "leader.vanguard",
  p2: "leader.relay",
} as const satisfies Readonly<Record<PlayerId, PrototypeLeaderId>>;

const deckPattern = [
  "entity.linebreaker",
  "entity.skywatcher",
  "entity.bulwark",
  "entity.flashrunner",
  "entity.ironhide",
  "entity.aegis",
  "entity.broodcaller",
  "entity.lastlight",
  "tactic.impact",
  "tactic.mend",
  "tactic.reposition",
  "tactic.displace",
  "tactic.recover",
  "tactic.survey",
  "reaction.deflect",
  "reaction.denial",
  "attachment.edge",
  "relic.beacon",
  "site.overlook",
  "tactic.stagger",
  "tactic.crossfire",
  "tactic.adapt",
] as const;

export const proofDeck: readonly string[] = Array.from(
  { length: 40 },
  (_, index) => deckPattern[index % deckPattern.length]!,
);
