import type { CardDefinition } from "@cardforge/card-schema";
import { stateHash } from "@cardforge/rules-kernel";

export const proofCards = [
  {
    cardId: "leader.vanguard",
    revision: 1,
    name: "Vanguard Marshal",
    type: "leader",
    aspects: ["force"],
    focusCost: 0,
    playTime: 0,
    abilities: [
      {
        abilityId: "marshal-command",
        type: "leader_command",
        focusCost: 1,
        timeCost: 2,
        oncePerCycle: true,
        effects: [
          { op: "deal_damage", target: { kind: "enemy_leader" }, amount: 1 },
        ],
      },
    ],
  },
  {
    cardId: "entity.linebreaker",
    revision: 1,
    name: "Linebreaker",
    type: "entity",
    aspects: ["force"],
    focusCost: 2,
    playTime: 2,
    power: 2,
    vitality: 3,
    presence: 1,
    strikeTime: 3,
  },
  {
    cardId: "entity.skywatcher",
    revision: 1,
    name: "Skywatcher",
    type: "entity",
    aspects: ["motion"],
    focusCost: 3,
    playTime: 3,
    power: 2,
    vitality: 3,
    presence: 1,
    strikeTime: 3,
    keywords: { ranged: true },
  },
  {
    cardId: "entity.bulwark",
    revision: 1,
    name: "Bulwark Array",
    type: "entity",
    subtypes: ["structure"],
    aspects: ["bastion"],
    focusCost: 3,
    playTime: 3,
    power: 0,
    vitality: 6,
    presence: 3,
    strikeTime: 3,
    keywords: { structure: true },
    slotRestriction: "support",
  },
  {
    cardId: "entity.flashrunner",
    revision: 1,
    name: "Flashrunner",
    type: "entity",
    aspects: ["motion"],
    focusCost: 2,
    playTime: 2,
    power: 2,
    vitality: 2,
    presence: 1,
    strikeTime: 2,
    keywords: { rapid: true, mobile: true },
  },
  {
    cardId: "entity.ironhide",
    revision: 1,
    name: "Ironhide Guard",
    type: "entity",
    aspects: ["bastion"],
    focusCost: 3,
    playTime: 3,
    power: 2,
    vitality: 4,
    presence: 2,
    strikeTime: 3,
    keywords: { armor: 1 },
  },
  {
    cardId: "entity.aegis",
    revision: 1,
    name: "Aegis Initiate",
    type: "entity",
    aspects: ["bastion"],
    focusCost: 2,
    playTime: 2,
    power: 1,
    vitality: 3,
    presence: 2,
    strikeTime: 3,
    keywords: { barrier: true },
  },
  {
    cardId: "tactic.impact",
    revision: 1,
    name: "Focused Impact",
    type: "tactic",
    aspects: ["force"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "impact",
        type: "activated",
        effects: [
          {
            op: "deal_damage",
            target: { kind: "chosen_enemy_entity" },
            amount: 3,
          },
        ],
      },
    ],
  },
  {
    cardId: "tactic.mend",
    revision: 1,
    name: "Field Mend",
    type: "tactic",
    aspects: ["growth"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "mend",
        type: "activated",
        effects: [
          { op: "heal", target: { kind: "chosen_friendly_entity" }, amount: 3 },
        ],
      },
    ],
  },
  {
    cardId: "tactic.reposition",
    revision: 1,
    name: "Reposition",
    type: "tactic",
    aspects: ["motion"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "reposition",
        type: "activated",
        effects: [{ op: "shift", target: { kind: "chosen_friendly_entity" } }],
      },
    ],
  },
  {
    cardId: "tactic.displace",
    revision: 1,
    name: "Forced Displacement",
    type: "tactic",
    aspects: ["cunning"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "displace",
        type: "activated",
        effects: [{ op: "shift", target: { kind: "chosen_enemy_entity" } }],
      },
    ],
  },
  {
    cardId: "entity.broodcaller",
    revision: 1,
    name: "Broodcaller",
    type: "entity",
    aspects: ["growth"],
    focusCost: 3,
    playTime: 3,
    power: 2,
    vitality: 4,
    presence: 1,
    strikeTime: 3,
    abilities: [
      {
        abilityId: "brood",
        type: "triggered",
        trigger: "on_deploy",
        effects: [{ op: "spawn", tokenCardId: "token.sprout" }],
      },
    ],
  },
  {
    cardId: "token.sprout",
    revision: 1,
    name: "Sprout",
    type: "token",
    aspects: ["growth"],
    focusCost: 0,
    playTime: 0,
    power: 1,
    vitality: 1,
    presence: 1,
    strikeTime: 3,
    generatedOnly: true,
  },
  {
    cardId: "attachment.edge",
    revision: 1,
    name: "Tempered Edge",
    type: "attachment",
    aspects: ["force"],
    focusCost: 1,
    playTime: 1,
    abilities: [{ abilityId: "edge", type: "static", effects: [] }],
  },
  {
    cardId: "relic.beacon",
    revision: 1,
    name: "Signal Beacon",
    type: "relic",
    aspects: ["neutral"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "beacon",
        type: "activated",
        effects: [{ op: "scout", amount: 2 }],
      },
    ],
  },
  {
    cardId: "site.overlook",
    revision: 1,
    name: "High Overlook",
    type: "site",
    aspects: ["neutral"],
    focusCost: 2,
    playTime: 2,
    abilities: [{ abilityId: "overlook", type: "static", effects: [] }],
  },
  {
    cardId: "reaction.deflect",
    revision: 1,
    name: "Deflect",
    type: "reaction",
    aspects: ["bastion"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "deflect",
        type: "reaction",
        effects: [
          { op: "add_barrier", target: { kind: "chosen_friendly_entity" } },
        ],
      },
    ],
  },
  {
    cardId: "reaction.denial",
    revision: 1,
    name: "Hard Denial",
    type: "reaction",
    aspects: ["cunning"],
    focusCost: 2,
    playTime: 2,
    abilities: [{ abilityId: "denial", type: "reaction", effects: [] }],
  },
  {
    cardId: "tactic.recover",
    revision: 1,
    name: "Recover the Fallen",
    type: "tactic",
    aspects: ["entropy"],
    focusCost: 2,
    playTime: 2,
    abilities: [
      {
        abilityId: "recover",
        type: "activated",
        effects: [{ op: "salvage", cardType: "entity" }],
      },
    ],
  },
  {
    cardId: "tactic.survey",
    revision: 1,
    name: "Survey the Line",
    type: "tactic",
    aspects: ["motion"],
    focusCost: 1,
    playTime: 1,
    abilities: [
      {
        abilityId: "survey",
        type: "activated",
        effects: [{ op: "scout", amount: 3 }],
      },
    ],
  },
  {
    cardId: "entity.lastlight",
    revision: 1,
    name: "Lastlight Warden",
    type: "entity",
    aspects: ["entropy"],
    focusCost: 2,
    playTime: 2,
    power: 2,
    vitality: 2,
    presence: 1,
    strikeTime: 3,
    abilities: [
      {
        abilityId: "lastlight",
        type: "triggered",
        trigger: "on_defeat",
        effects: [
          { op: "heal", target: { kind: "friendly_leader" }, amount: 2 },
        ],
      },
    ],
  },
] as const satisfies readonly CardDefinition[];

export const proofCardMap: ReadonlyMap<string, CardDefinition> = new Map(
  proofCards.map((card) => [card.cardId, card]),
);
export const proofContentHash = stateHash(proofCards);

const deckPattern = [
  "entity.linebreaker",
  "entity.skywatcher",
  "entity.bulwark",
  "entity.flashrunner",
  "entity.ironhide",
  "entity.aegis",
  "entity.broodcaller",
  "entity.lastlight",
  "tactic.impact",
  "tactic.mend",
  "tactic.reposition",
  "tactic.displace",
  "tactic.recover",
  "tactic.survey",
] as const;

export const proofDeck: readonly string[] = Array.from(
  { length: 40 },
  (_, index) => deckPattern[index % deckPattern.length]!,
);
